In [2]:
import pandas as pd
#df3 = Dataframe from a List of List
indexList = list()
for i in range(20, 30):
    indexList.append(i+1)

tempList  = [['Sarjana', 'Sains dan Teknologi', 'Teknik Mesin', '459'], ['Sarjana', 'Sains dan Teknologi', 'Informatika', '738'], ['Sarjana', 'Farmasi', 'Farmasi', '720'], ['Sarjana', 'Psikologi', 'Psikologi', '969'], ['Sarjana', 'Teologi', 'Filsafat Keilahian ', '312'], ['Magister', 'Keguruan dan Ilmu Pendidikan', 'Magister Pendidikan Bahasa Inggris', '27'], ['Magister', 'Keguruan dan Ilmu Pendidikan', 'Magister Pendidikan Bahasa Indonesia', '22'], ['Magister', 'Keguruan dan Ilmu Pendidikan', 'Magister Pendidikan Matematika', '20'], ['Magister', 'Farmasi', 'Magister Farmasi', '68'], ['Magister', 'Ekonomi', 'Magister Manajemen', '71']]

col=["Program", "Fakultas", "Prodi", "Jumlah"]
df3=pd.DataFrame(tempList,index= indexList,columns = col)

In [3]:
df3

,Program,Fakultas,Prodi,Jumlah
21,Sarjana,Sains dan Teknologi,Teknik Mesin,459
22,Sarjana,Sains dan Teknologi,Informatika,738
23,Sarjana,Farmasi,Farmasi,720
24,Sarjana,Psikologi,Psikologi,969
25,Sarjana,Teologi,Filsafat Keilahian,312
26,Magister,Keguruan dan Ilmu Pendidikan,Magister Pendidikan Bahasa Inggris,27
27,Magister,Keguruan dan Ilmu Pendidikan,Magister Pendidikan Bahasa Indonesia,22
28,Magister,Keguruan dan Ilmu Pendidikan,Magister Pendidikan Matematika,20
29,Magister,Farmasi,Magister Farmasi,68
30,Magister,Ekonomi,Magister Manajemen,71